flowchart TD
	node1["01_ENVELOPE-ENV_STG01_MASSING"]
	node2["01_ENVELOPE-ENV_STG02_LEVELS"]
	node3["01_REFERENCE-REF_FLOORS"]
	node4["02_PANELS-01_WF-PAN_WF_STG01_Joints"]
	node5["project\00_REFERENCE\REF_FLOORS\REF_FLOORS.gh.dvc"]
	node6["project\01_ENVELOPE\ENV_STG01_MASSING\ENV_STG01_Massing.gh.dvc"]
	node7["project\01_ENVELOPE\ENV_STG02_LEVELS\ENV_STG02_LEVELS.gh.dvc"]
	node8["project\02_PANELS\01_WF\PAN_WF_STG01_Joints\PAN_WF_STG01_Joints.gh.dvc"]
	node1-->node2
	node2-->node4
	node3-->node2
	node5-->node3
	node6-->node1
	node7-->node2
	node8-->node4
	node9["project\00_REFERENCE\REF_FLOORS\REF_FLOORS.rws.dvc"]
	node10["project\01_ENVELOPE\ENV_STG01_MASSING\ENV_STG01_Massing.rws.dvc"]
	node11["project\01_ENVELOPE\ENV_STG02_LEVELS\ENV_STG02_LEVELS.rws.dvc"]
	node12["project\01_ENVELOPE\ENV_STG03_PANELS\ENV_STG03_PANELS.3dm.dvc"]
	node13["project\02_PANELS\01_WF\PAN_WF_STG02_Outlines.3dm.dvc"]
	node14["project\02_PANELS\01_WF\PAN_WF_STG01_Joints\PAN_WF_STG01_Joints.rws.dvc"]
	node15["project\02_PANELS\01_WF\PAN_WF_STG02_Outlines\PAN_WF_STG02_Outlines.3dm.dvc"]
	node16["project\02_PANELS\01_WF\PAN_WF_STG02_Outlines\PAN_WF_STG02_Outlines.gh.dvc"]
	node17["project\02_PANELS\01_WF\PAN_WF_STG02_Outlines\PAN_WF_STG02_Outlines.rws.dvc"]
	node18["project\03_BRACKETS\BRK_STG01_Blocks\BRK_STG01_Blocks.3dm.dvc"]
	node19["project\03_BRACKETS\BRK_STG01_Blocks\BRK_STG01_Blocks.gh.dvc"]
	node20["project\XX_BLOCKS\FRAMING\COMPONENTS\Double_IGU.3dm.dvc"]
	node21["project\XX_BLOCKS\FRAMING\COMPONENTS\Mullion_Left.3dm.dvc"]
	node22["project\XX_BLOCKS\FRAMING\COMPONENTS\Mullion_Right.3dm.dvc"]
	node23["project\XX_BLOCKS\FRAMING\COMPONENTS\Transom_Bottom.3dm.dvc"]
	node24["project\XX_BLOCKS\FRAMING\COMPONENTS\Transom_Clip1.3dm.dvc"]
	node25["project\XX_BLOCKS\FRAMING\COMPONENTS\Transom_Clip2.3dm.dvc"]
	node26["project\XX_BLOCKS\FRAMING\COMPONENTS\Transom_Clip_Primary.3dm.dvc"]
	node27["project\XX_BLOCKS\FRAMING\COMPONENTS\Transom_Top.3dm.dvc"]
	node28["project\XX_BLOCKS\FRAMING\Ref\Kawneer_2500_UT.3dm.dvc"]
	node29["project\XX_BLOCKS\FRAMING\Ref\Kawneer_2500_UT_TypicalMullion.3dm.dvc"]
	node30["project\XX_BLOCKS\FRAMING\Ref\Kawneer_2500_UT_TypicalStack.3dm.dvc"]
	node31["project\XX_BLOCKS\LCS\LCS.3dm.dvc"]
	node32["project\XX_CLUSTERS\Integer String Length.ghuser.dvc"]
	node33["project\XX_CLUSTERS\Plane to String.ghuser.dvc"]
	node34["project\XX_CLUSTERS\String to Plane.ghuser.dvc"]
	node35["project\XX_Examples\AEC_Tech_Working_File.gh.dvc"]
	node36["project\XX_Examples\BakeToFile_01.3dm.dvc"]
	node37["project\XX_Examples\BakeToFile_02.3dm.dvc"]
	node38["project\XX_Examples\BakeToFile_03.3dm.dvc"]
	node39["project\XX_Examples\BakeToFile_04.3dm.dvc"]
	node40["project\XX_Examples\Exp3dm.3dm.dvc"]
	node41["project\XX_Examples\Exported_Block.3dm.dvc"]
	node42["project\XX_Examples\Export_Example.3dm.dvc"]
	node43["project\XX_Examples\Export_Spheres.3dm.dvc"]
	node44["project\XX_Examples\Test Worksession.rws.dvc"]
	node45["project\XX_Examples\Working_File.3dm.dvc"]
	node46["project\XX_Examples\OUTPUT\001.3dm.dvc"]
	node47["project\XX_Examples\OUTPUT\002.3dm.dvc"]
	node48["project\XX_Examples\OUTPUT\003.3dm.dvc"]
	node49["project\XX_Examples\OUTPUT\004.3dm.dvc"]
	node50["project\XX_Examples\OUTPUT\005.3dm.dvc"]
	node51["project\XX_Examples\OUTPUT\006.3dm.dvc"]
	node52["project\XX_Examples\OUTPUT\007.3dm.dvc"]
	node53["project\XX_Examples\OUTPUT\008.3dm.dvc"]
	node54["project\XX_Examples\OUTPUT\009.3dm.dvc"]
	node55["project\XX_Examples\OUTPUT\010.3dm.dvc"]
	node56["project\XX_Examples\OUTPUT\011.3dm.dvc"]
	node57["project\XX_Examples\OUTPUT\012.3dm.dvc"]
	node58["project\XX_Examples\OUTPUT\013.3dm.dvc"]
	node59["project\XX_Examples\OUTPUT\014.3dm.dvc"]
	node60["project\XX_Examples\OUTPUT\015.3dm.dvc"]
	node61["project\XX_Examples\OUTPUT\016.3dm.dvc"]
	node62["project\XX_Examples\OUTPUT\017.3dm.dvc"]
	node63["project\XX_Examples\OUTPUT\018.3dm.dvc"]
	node64["project\XX_Examples\OUTPUT\019.3dm.dvc"]
	node65["project\XX_Examples\OUTPUT\020.3dm.dvc"]
	node66["project\XX_Examples\OUTPUT\021.3dm.dvc"]
	node67["project\XX_Examples\OUTPUT\022.3dm.dvc"]
	node68["project\XX_Examples\OUTPUT\023.3dm.dvc"]
	node69["project\XX_Examples\OUTPUT\024.3dm.dvc"]
	node70["project\XX_Examples\OUTPUT\025.3dm.dvc"]
	node71["project\XX_Examples\OUTPUT\026.3dm.dvc"]
	node72["project\XX_Examples\OUTPUT\027.3dm.dvc"]
	node73["project\XX_Examples\OUTPUT\028.3dm.dvc"]
	node74["project\XX_Examples\OUTPUT\029.3dm.dvc"]
	node75["project\XX_Examples\OUTPUT\030.3dm.dvc"]
	node76["project\XX_Examples\OUTPUT\031.3dm.dvc"]
	node77["project\XX_Examples\OUTPUT\032.3dm.dvc"]
	node78["project\XX_Examples\OUTPUT\033.3dm.dvc"]
	node79["project\XX_Examples\OUTPUT\034.3dm.dvc"]
	node80["project\XX_Examples\OUTPUT\035.3dm.dvc"]
	node81["project\XX_Examples\OUTPUT\036.3dm.dvc"]
	node82["project\XX_Examples\OUTPUT\037.3dm.dvc"]
	node83["project\XX_Examples\OUTPUT\038.3dm.dvc"]
	node84["project\XX_Examples\OUTPUT\039.3dm.dvc"]
