flowchartTD
	node1["01_ENVELOPE-ENV_STG01_MASSING"]
	node2["01_ENVELOPE-ENV_STG02_LEVELS"]
	node3["01_REFERENCE-REF_FLOORS"]
	node4["02_PANELS-01_WF-PAN_WF_STG01_Joints"]
	node5["project00_REFERENCEREF_FLOORSREF_FLOORS"]
	node6["project01_ENVELOPEENV_STG01_MASSINGENV_STG01_Massing"]
	node7["project01_ENVELOPEENV_STG02_LEVELSENV_STG02_LEVELS"]
	node8["project02_PANELS01_WFPAN_WF_STG01_JointsPAN_WF_STG01_Joints"]
	node1-->node2
	node2-->node4
	node3-->node2
	node5-->node3
	node6-->node1
	node7-->node2
	node8-->node4
	node9-->node10
	node10-->node13
	node11-->node12
	node12-->node13
	node13-->node14
	node14-->node15
	node15-->node16
	node16-->node18
	node17-->node16
	node18-->node19
	node19-->node20
	node20-->node23
	node21-->node24
	node22-->node23
	node23-->node14
	node24-->node25
	node25-->node26
	node9["project02_PANELS01_WFPAN_WF_STG02_Outlines"]
	node10["project02_PANELS01_WFPAN_WF_STG02_OutlinesPAN_WF_STG02_Outlines"]
	node11["project02_PANELS01_WFPAN_WF_STG02_OutlinesPAN_WF_STG02_Outlines"]
	node12["project02_PANELS01_WFPAN_WF_STG02_OutlinesPAN_WF_STG02_Outlines"]
	node13["project02_PANELS01_WFPAN_WF_STG01_JointsPAN_WF_STG01_Joints"]
	node14["projectXX_CLUSTERSPlanetoString.ghuser"]
	node15["projectXX_CLUSTERSStringtoPlane.ghuser"]
	node16["projectXX_CLUSTERSIntegerStringLength.ghuser"]
	node17["project01_ENVELOPEENV_STG01_MASSINGENV_STG01_Massing"]
	node18["project01_ENVELOPEENV_STG02_LEVELSENV_STG02_LEVELS"]
	node19["project01_ENVELOPEENV_STG03_PANELSENV_STG03_PANELS"]
	node20["projectXX_BLOCKSLCSLCS"]
	node21["projectXX_BLOCKSFRAMINGRefKawneer_2500_UT_TypicalMullion"]
	node22["projectXX_BLOCKSFRAMINGRefKawneer_2500_UT_TypicalStack"]
	node23["projectXX_BLOCKSFRAMINGRefKawneer_2500_UT"]
	node24["projectXX_BLOCKSFRAMINGCOMPONENTSMullion_Left"]
	node25["projectXX_BLOCKSFRAMINGCOMPONENTSTransom_Bottom"]
	node26["projectXX_BLOCKSFRAMINGCOMPONENTSMullion_Right"]
	node27["projectXX_BLOCKSFRAMINGCOMPONENTSDouble_IGU"]
	node28["projectXX_BLOCKSFRAMINGCOMPONENTSTransom_Clip1"]
	node29["projectXX_BLOCKSFRAMINGCOMPONENTSTransom_Clip_Primary"]
	node30["projectXX_BLOCKSFRAMINGCOMPONENTSTransom_Clip2"]
	node31["projectXX_BLOCKSFRAMINGCOMPONENTSTransom_Top"]
	node32["project03_BRACKETSBRK_STG01_BlocksBRK_STG01_Blocks"]
	node33["project03_BRACKETSBRK_STG01_BlocksBRK_STG01_Blocks"]
	node34["projectXX_ExamplesBakeToFile_04"]
	node35["projectXX_ExamplesExp3dm"]
	node36["projectXX_ExamplesExport_Spheres"]
	node37["projectXX_ExamplesTestWorksession"]
	node38["projectXX_ExamplesBakeToFile_02"]
	node39["projectXX_ExamplesExport_Example"]
	node40["projectXX_ExamplesAEC_Tech_Working_File"]
	node41["projectXX_ExamplesExported_Block"]
	node42["projectXX_ExamplesBakeToFile_03"]
	node43["projectXX_ExamplesBakeToFile_01"]
	node44["projectXX_ExamplesWorking_File"]
	node45["projectXX_ExamplesOUTPUT027"]
	node46["projectXX_ExamplesOUTPUT037"]
	node47["projectXX_ExamplesOUTPUT018"]
	node48["projectXX_ExamplesOUTPUT008"]
	node49["projectXX_ExamplesOUTPUT001"]
	node50["projectXX_ExamplesOUTPUT011"]
	node51["projectXX_ExamplesOUTPUT010"]
	node52["projectXX_ExamplesOUTPUT036"]
	node53["projectXX_ExamplesOUTPUT026"]
	node54["projectXX_ExamplesOUTPUT009"]
	node55["projectXX_ExamplesOUTPUT019"]
	node56["projectXX_ExamplesOUTPUT002"]
	node57["projectXX_ExamplesOUTPUT012"]
	node58["projectXX_ExamplesOUTPUT024"]
	node59["projectXX_ExamplesOUTPUT034"]
	node60["projectXX_ExamplesOUTPUT035"]
	node61["projectXX_ExamplesOUTPUT025"]
	node62["projectXX_ExamplesOUTPUT013"]
	node63["projectXX_ExamplesOUTPUT003"]
	node64["projectXX_ExamplesOUTPUT006"]
	node65["projectXX_ExamplesOUTPUT016"]
	node66["projectXX_ExamplesOUTPUT039"]
	node67["projectXX_ExamplesOUTPUT029"]
	node68["projectXX_ExamplesOUTPUT020"]
	node69["projectXX_ExamplesOUTPUT030"]
	node70["projectXX_ExamplesOUTPUT031"]
	node71["projectXX_ExamplesOUTPUT021"]
	node72["projectXX_ExamplesOUTPUT017"]
	node73["projectXX_ExamplesOUTPUT007"]
	node74["projectXX_ExamplesOUTPUT028"]
	node75["projectXX_ExamplesOUTPUT038"]
	node76["projectXX_ExamplesOUTPUT023"]
	node77["projectXX_ExamplesOUTPUT033"]
	node78["projectXX_ExamplesOUTPUT005"]
	node79["projectXX_ExamplesOUTPUT015"]
	node80["projectXX_ExamplesOUTPUT014"]
	node81["projectXX_ExamplesOUTPUT004"]
	node82["projectXX_ExamplesOUTPUT032"]
	node83["projectXX_ExamplesOUTPUT022"]
	node84["project00_REFERENCEREF_FLOORSREF_FLOORS"]