[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Max Dumas", email = "max@dumas.nyc"},
]
dependencies = [
    "dvc>=3.28.0",
    "dvc-s3>=2.23.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

